types: Fix Relay authTitle type (#418)
authType is a string. It was corrected in commit 8507286895b6c1f0382d70f398f3127bd473b14c but this particular change was overlooked.

This solves the error:

node_modules/bedrock-protocol/index.d.ts:177:17 - error TS2304: Cannot find name 'title'.

177     authTitle?: title | string
                    ~~~~~


Found 1 error in node_modules/bedrock-protocol/index.d.ts:177